// Country : Capital
var answerKey = { 
	"Nigeria" : "Abuja" ,
	"Ghana" : "Accra" ,
	"Ethiopia" : "Addis Ababa" ,
	"Algeria" : "Algiers" ,
	"Madagascar" : "Antananarivo" ,
	"Eritrea" : "Asmara" ,
	"Mali" : "Bamako" ,
	"Central African Republic" : "Bangui" ,
	"Gambia" : "Banjul" ,
	"Guinea-Bissau" : "Bissau" ,
	"Republic of Congo" : "Brazzaville" ,
	"Burundi" : "Bujumbura" ,
	"Egypt" : "Cairo" ,
	"South Africa" : "Cape Town" ,
	"Guinea" : "Conakry" ,
	"Senegal" : "Dakar" ,
	"Tanzania" : "Dar es Salaam" ,
	"Djibouti" : "Djibouti" ,
	"Sierra Leone" : "Freetown" ,
	"Botswana" : "Gaborone" ,
	"Zimbabwe" : "Harare" ,
	"South Sudan" : "Juba" ,
	"Uganda" : "Kampala" ,
	"Sudan" : "Khartoum" ,
	"Rwanda" : "Kigali" ,
	"Dem. Rep. of the Congo" : "Kinshasa" ,
	"Western Sahara" : "El Aaiun" ,
	"Gabon" : "Libreville" ,
	"Malawi" : "Lilongwe" ,
	"Swaziland" : "Mbabane" ,
	"Togo" : "Lome" ,
	"Angola" :"Luanda" ,
	"Zambia" : "Lusaka" ,
	"Equatorial Guinea" : "Malabo" ,
	"Mozambique" : "Maputo" ,
	"Lesotho" : "Maseru" ,
	"Somalia" : "Mogadishu" ,
	"Liberia" : "Monrovia" ,
	"Comoros" : "Moroni" ,
	"Kenya" : "Nairobi" ,
	"Chad" : "N'Djamena" ,
	"Niger" : "Niamey" ,
	"Mauritania" : "Nouakchott" ,
	"Burkina Faso" : "Ouagadougou" ,
	"Mauritius" : "Port Louis" ,
	"Benin" : "Porto-Novo" ,
	"Cape Verde" : "Praia" ,
	"Morocco" : "Rabat" ,
	"Libya" : "Tripoli" ,
	"Tunisia" : "Tunis" ,
	"Seychelles" : "Victoria" ,
	"Namibia" : "Windhoek" ,
	"Ivory Coast" : "Yamoussoukro" ,
	"Cameroon" : "Yaounde"
}